package com.bcs.zsg.maintenance.helper;

public enum ConstantAppSetting {
	
	/*	MAIN module active status 	*/
	MODULE_MAINT("MAINT"),
	MODULE_SALES("SALES"),
	MODULE_ADMIN("ADMIN"),
	
	// MAINT_AUTO_E_INV_CONFIG_DEP_DT("MAINT_AUTO_E_INV_CONFIG_DEP_DT"), // XXX this is only for testing (You Yuan)
	MAINT_POS_CONFIG_UPLOAD_AS_TEST("MAINT_POS_CONFIG_UPLOAD_AS_TEST"),
	MAINT_POS_CONFIG_SCHEDULER_TIME_UPLOAD("MAINT_POS_CONFIG_SCHEDULER_TIME_UPLOAD"),
	MAINT_POS_CONFIG_GL_ACCT_TO_EXCLUDE("MAINT_POS_CONFIG_GL_ACCT_TO_EXCLUDE"),
	MAINT_IPAY88_EXPIRY_DURATION("MAINT_IPAY88_EXPIRY_DURATION"),
	SALES_TOUR_DEPARTURE_DISCOUNT_LIMIT("SALES_TOUR_DEPARTURE_DISCOUNT_LIMIT"),
	SALES_TOUR_PACKAGE_COMMISION_LIMIT("SALES_TOUR_PACKAGE_COMMISION_LIMIT"),
	ADMIN_TOUR_DEP_ITINERARY_FROM_CMS("ADMIN_TOUR_DEP_ITINERARY_FROM_CMS"),
	ADMIN_TOUR_PKG_DEP_LIST_FILTER_FUNC("ADMIN_TOUR_PKG_DEP_LIST_FILTER_FUNC"),
	ADMIN_INCL_INFT_IN_ALLOTMENT_CALC_IN_OUTBOUND("ADMIN_INCL_INFT_IN_ALLOTMENT_CALC_IN_OUTBOUND"),
	ADMIN_BOOKING_ALLOW_REACTIVATE("ADMIN_BOOKING_ALLOW_REACTIVATE"),
	ADMIN_AGENT_DEP_LIST_SHOW_SEAT_ALLOTMENT("ADMIN_AGENT_DEP_LIST_SHOW_SEAT_ALLOTMENT"),
	MAINT_CUSTOMER_PROFILE_UPDATE_EXPIRY_DURATION("MAINT_CUSTOMER_PROFILE_UPDATE_EXPIRY_DURATION"),
	MAINT_SUPPLIER_PROFILE_UPDATE_EXPIRY_DURATION("MAINT_SUPPLIER_PROFILE_UPDATE_EXPIRY_DURATION"),
	MAINT_REVERSE_SALES_JOURNAL_SCHEDULER("MAINT_REVERSE_SALES_JOURNAL_SCHEDULER"),
	MAINT_JOURNAL_CONFIG_SCHEDULER_TIME_PROCESS_REVERSE_SALES("MAINT_JOURNAL_CONFIG_SCHEDULER_TIME_PROCESS_REVERSE_SALES"),
	MAINT_AUTO_SUBMIT_E_INV_SCHEDULER("MAINT_AUTO_SUBMIT_E_INV_SCHEDULER"),
	MAINT_AUTO_E_INV_CONFIG_SCHEDULER_SUBMIT_TIME_1("MAINT_AUTO_E_INV_CONFIG_SCHEDULER_SUBMIT_TIME_1"),
	MAINT_AUTO_DAILY_REFRESH_E_INV_SCHEDULER("MAINT_AUTO_DAILY_REFRESH_E_INV_SCHEDULER"),
	MAINT_AUTO_E_INV_CONFIG_SCHEDULER_REFRESH_TIME("MAINT_AUTO_E_INV_CONFIG_SCHEDULER_REFRESH_TIME"),
	MAINT_AUTO_REFRESH_E_INV_SUBMISSION_SCHEDULER("MAINT_AUTO_REFRESH_E_INV_SUBMISSION_SCHEDULER"),
	MAINT_AUTO_E_INV_CONFIG_SCHEDULER_REFRESH_SUB_INTERVAL("MAINT_AUTO_E_INV_CONFIG_SCHEDULER_REFRESH_SUB_INTERVAL"),
	MAINT_AUTO_E_INV_CONFIG_SCHEDULER_SUBMIT_INV_CAT("MAINT_AUTO_E_INV_CONFIG_SCHEDULER_SUBMIT_INV_CAT"),
	MAINT_FEEDBACK_EMAIL_SCHEDULER_TIME("MAINT_FEEDBACK_EMAIL_SCHEDULER_TIME"),
	MAINT_FEEDBACK_EMAIL_SCHEDULER("MAINT_FEEDBACK_EMAIL_SCHEDULER");
	
	
	private String value;

    private ConstantAppSetting(String value) {
        this.value = value;
    }
    public String getValue() {
        return value;
    }
    public static ConstantAppSetting getNameByCode(String code) {
    	for (ConstantAppSetting e : ConstantAppSetting.values()) {
    		if (code.equals(e.value)) return e;
	  	}
	  return null;
	}
}
