-- Functions
-- Sales
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES', 'SALES', 'Sales', 'T', '#', '', '1', 1, 10, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Sales -> Customer
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CUST', 'SALES_CUST', 'Customer', 'L', '#', '', '1', 2, 1, 'U_SALES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CUST_MAINT', 'SALES_CUST_MAINT', 'Customer Maintenance', 'L', '/app/sales/cust/maint', '', '1', 3, 1, 'U_SALES_CUST', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CUST_SEARCH', 'SALES_CUST_SEARCH', 'Customer Search', 'L', '/app/sales/cust/search', '', '1', 3, 2, 'U_SALES_CUST', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Sales -> Invoice
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_INV', 'SALES_INV', 'Invoice', 'L', '#', '', '1', 2, 2, 'U_SALES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_INV_ISSUANCE', 'SALES_INV_ISSUANCE', 'Invoice Issuance', 'L', '/app/sales/inv/issuance', '', '1', 3, 1, 'U_SALES_INV', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_INV_SEARCH', 'SALES_INV_SEARCH', 'Invoice Search', 'L', '/app/sales/inv/search', '', '1', 3, 2, 'U_SALES_INV', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_INV_PRINT', 'SALES_INV_PRINT', 'Invoice Printing', 'L', '/app/sales/inv/print', '', '1', 3, 3, 'U_SALES_INV', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Sales -> Credit Note
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CREDITNOTE', 'SALES_CREDITNOTE', 'Credit Note', 'L', '#', '', '1', 2, 3, 'U_SALES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CREDITNOTE_ISSUANCE', 'SALES_CREDITNOTE_ISSUANCE', 'Credit Note Issuance', 'L', '/app/sales/creditnote/issuance', '', '1', 3, 1, 'U_SALES_CREDITNOTE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_CREDITNOTE_SEARCH', 'SALES_CREDITNOTE_SEARCH', 'Credit Note Search', 'L', '/app/sales/creditnote/search', '', '1', 3, 2, 'U_SALES_CREDITNOTE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Sales -> Debtor Statements
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_DEBTORSTMT', 'SALES_DEBTORSTMT', 'Debtor Statements', 'L', '#', '', '1', 2, 3, 'U_SALES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SALES_DEBTORSTMT_GENERATE', 'SALES_DEBTORSTMT_GENERATE', 'Generate Customer Statements', 'L', '/app/sales/debtorstmt/generate', '', '1', 3, 1, 'U_SALES_DEBTORSTMT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- Product
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT', 'PRODUCT', 'Product', 'T', '#', '', '1', 1, 11, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Product -> Series
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_SERIES', 'PRODUCT_SERIES', 'Tour Series', 'L', '#', '', '1', 2, 1, 'U_PRODUCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_SERIES_MAINT', 'PRODUCT_SERIES_MAINT', 'Tour Series Maintenance', 'L', '/app/product/series/maint', '', '1', 3, 1, 'U_PRODUCT_SERIES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_SERIES_SEARCH', 'PRODUCT_SERIES_SEARCH', 'Tour Series Search', 'L', '/app/product/series/search', '', '1', 3, 2, 'U_PRODUCT_SERIES', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Product -> Master
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_MASTER', 'PRODUCT_MASTER', 'Tour Master', 'L', '#', '', '1', 2, 1, 'U_PRODUCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_MASTER_MAINT', 'PRODUCT_MASTER_MAINT', 'Tour Master Maintenance', 'L', '/app/product/master/maint', '', '1', 3, 1, 'U_PRODUCT_MASTER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PRODUCT_MASTER_SEARCH', 'PRODUCT_MASTER_SEARCH', 'Tour Master Search', 'L', '/app/product/master/search', '', '1', 3, 2, 'U_PRODUCT_MASTER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- Purchases
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE', 'PURCHASE', 'Purchases', 'T', '#', '', '1', 1, 12, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Purchases -> Supplier
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_SUPPLIER', 'PURCHASE_SUPPLIER', 'Supplier', 'L', '#', '', '1', 2, 1, 'U_PURCHASE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_SUPPLIER_MAINT', 'PURCHASE_SUPPLIER_MAINT', 'Supplier Maintenance', 'L', '/app/purchase/supplier/maint', '', '1', 3, 1, 'U_PURCHASE_SUPPLIER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_SUPPLIER_SEARCH', 'PURCHASE_SUPPLIER_SEARCH', 'Supplier Search', 'L', '/app/purchase/supplier/search', '', '1', 3, 2, 'U_PURCHASE_SUPPLIER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_SUPPLIER_SEARCHBAL', 'PURCHASE_SUPPLIER_SEARCHBAL', 'Supplier Search with Balance', 'L', '/app/purchase/supplier/searchbal', '', '1', 3, 3, 'U_PURCHASE_SUPPLIER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Purchases -> Exchange Order
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_EXORDER', 'PURCHASE_EXORDER', 'Exchange Order', 'L', '#', '', '1', 2, 2, 'U_PURCHASE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_EXORDER_MAINT', 'PURCHASE_EXORDER_MAINT', 'Exchange Order Maintenance', 'L', '/app/purchase/exorder/maint', '', '1', 3, 1, 'U_PURCHASE_EXORDER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_EXORDER_SEARCH', 'PURCHASE_EXORDER_SEARCH', 'Exchange Order Search', 'L', '/app/purchase/exorder/search', '', '1', 3, 2, 'U_PURCHASE_EXORDER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Purchases -> Bills
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_BILL', 'PURCHASE_BILL', 'Bills', 'L', '#', '', '1', 2, 3, 'U_PURCHASE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_BILL_PMNT', 'PURCHASE_BILL_PMNT', 'Bills Payment', 'L', '/app/purchase/bill/pmnt', '', '1', 3, 1, 'U_PURCHASE_BILL', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_PURCHASE_BILL_SEARCH', 'PURCHASE_BILL_SEARCH', 'Bills Search', 'L', '/app/purchase/bill/search', '', '1', 3, 2, 'U_PURCHASE_BILL', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- Banking
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK', 'BANK', 'Banking', 'T', '#', '', '1', 1, 13, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Banking -> Bank/Cash
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_BANKCASH', 'BANK_BANKCASH', 'Bank/Cash', 'L', '#', '', '1', 2, 1, 'U_BANK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_BANKCASH_MAINT', 'BANK_BANKCASH_MAINT', 'Bank/Cash Maintenance', 'L', '/app/bank/bankcash/maint', '', '1', 3, 1, 'U_BANK_BANKCASH', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_BANKCASH_SEARCH', 'BANK_BANKCASH_SEARCH', 'Bank/Cash Search', 'L', '/app/bank/bankcash/search', '', '1', 3, 2, 'U_BANK_BANKCASH', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Banking -> Receipt/Deposit
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RCPT', 'BANK_RCPT', 'Receipt/Deposit', 'L', '#', '', '1', 2, 2, 'U_BANK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RCPT_MAINT', 'BANK_RCPT_MAINT', 'Receipt/Deposit Maintenance', 'L', '/app/bank/rcpt/maint', '', '1', 3, 1, 'U_BANK_RCPT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RCPT_SEARCH', 'BANK_RCPT_SEARCH', 'Receipt/Deposit Search', 'L', '/app/bank/rcpt/search', '', '1', 3, 2, 'U_BANK_RCPT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Banking -> Bank Adjustment
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_ADJUSTMENT', 'BANK_ADJUSTMENT', 'Bank Adjustment', 'L', '#', '', '1', 2, 3, 'U_BANK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_ADJUSTMENT_MAINT', 'BANK_ADJUSTMENT_MAINT', 'Bank Adjustment Maintenance', 'L', '/app/bank/adjustment/maint', '', '1', 3, 1, 'U_BANK_ADJUSTMENT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_ADJUSTMENT_SEARCH', 'BANK_ADJUSTMENT_SEARCH', 'Bank Adjustment Search', 'L', '/app/bank/adjustment/search', '', '1', 3, 2, 'U_BANK_ADJUSTMENT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Banking -> Cash Book
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_CASHBOOK', 'BANK_CASHBOOK', 'Cash Book', 'L', '#', '', '1', 2, 4, 'U_BANK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_CASHBOOK_MAINT', 'BANK_CASHBOOK_MAINT', 'Cash Book Maintenance', 'L', '/app/bank/cashbook/maint', '', '1', 3, 1, 'U_BANK_CASHBOOK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_CASHBOOK_SEARCH', 'BANK_CASHBOOK_SEARCH', 'Cash Book Search', 'L', '/app/bank/cashbook/search', '', '1', 3, 2, 'U_BANK_CASHBOOK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Banking -> Reconciliation
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RECON', 'BANK_RECON', 'Reconciliation', 'L', '#', '', '1', 2, 5, 'U_BANK', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RECON_MAINT', 'BANK_RECON_MAINT', 'Reconciliation Maintenance', 'L', '/app/bank/recon/maint', '', '1', 3, 1, 'U_BANK_RECON', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_BANK_RECON_SEARCH', 'BANK_RECON_SEARCH', 'Reconciliation Search', 'L', '/app/bank/recon/search', '', '1', 3, 2, 'U_BANK_RECON', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- Accounting
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT', 'ACCT', 'Accounting', 'T', '#', '', '1', 1, 14, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Accounting -> Chart of Accounts
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_CHART', 'ACCT_CHART', 'Chart of Accounts', 'L', '#', '', '1', 2, 1, 'U_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_CHART_MAINT', 'ACCT_CHART_MAINT', 'Chart of Accounts Maintenance', 'L', '/app/acct/chart/maint', '', '1', 3, 1, 'U_ACCT_CHART', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_CHART_SEARCH', 'ACCT_CHART_SEARCH', 'Chart of Accounts Search', 'L', '/app/acct/chart/search', '', '1', 3, 2, 'U_ACCT_CHART', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Accounting -> Opening Balances
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_OPENBALANCE', 'ACCT_OPENBALANCE', 'Opening Balances', 'L', '#', '', '1', 2, 2, 'U_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_OPENBALANCE_MAINT', 'ACCT_OPENBALANCE_MAINT', 'Opening Balances Maintenance', 'L', '/app/acct/openbalance/maint', '', '1', 3, 1, 'U_ACCT_OPENBALANCE', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Accounting -> Financial Periods
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_FINANCIAL', 'ACCT_FINANCIAL', 'Financial Periods', 'L', '#', '', '1', 2, 3, 'U_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_FINANCIAL_MAINT', 'ACCT_FINANCIAL_MAINT', 'Financial Periods Maintenance', 'L', '/app/acct/financial/maint', '', '1', 3, 1, 'U_ACCT_FINANCIAL', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Accounting -> Journal Entries
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_JOURNAL', 'ACCT_JOURNAL', 'Journal Entries', 'L', '#', '', '1', 2, 4, 'U_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_JOURNAL_MAINT', 'ACCT_JOURNAL_MAINT', 'Journal Entries Maintenance', 'L', '/app/acct/journal/maint', '', '1', 3, 1, 'U_ACCT_JOURNAL', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_JOURNAL_SEARCH', 'ACCT_JOURNAL_SEARCH', 'Journal Entries Search', 'L', '/app/acct/journal/search', '', '1', 3, 2, 'U_ACCT_JOURNAL', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
-- Accounting -> General Ledger
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_LEDGER', 'ACCT_LEDGER', 'General Ledger', 'L', '#', '', '1', 2, 5, 'U_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_LEDGER_MAINT', 'ACCT_LEDGER_MAINT', 'General Ledger Maintenance', 'L', '/app/acct/ledger/maint', '', '1', 3, 1, 'U_ACCT_LEDGER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ACCT_LEDGER_SEARCH', 'ACCT_LEDGER_SEARCH', 'General Ledger Search', 'L', '/app/acct/ledger/search', '', '1', 3, 2, 'U_ACCT_LEDGER', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);















