USE bterpdb;

DROP TABLE IF EXISTS COM_SYS_PARAM;
CREATE TABLE COM_SYS_PARAM ( 
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	UUID			VARCHAR(50) NOT NULL COMMENT 'Unique record identifier.',
	APP_ID			VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	CAT_CD			VARCHAR(100) NOT NULL COMMENT 'Category code.',
	PARAM_CD		VARCHAR(100) NOT NULL COMMENT 'Parameter key.',
	PARAM_VALUE		VARCHAR(255) NOT NULL COMMENT 'Parameter value.',
	PARAM_DESC		VARCHAR(500) NOT NULL COMMENT 'A description of this parameter. Viewed by admin only.',
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT PK_COM_SYS_PARAM PRIMARY KEY (ID),
	CONSTRAINT UK_COM_SYS_PARAM1 UNIQUE KEY (UUID),
	CONSTRAINT UK_COM_SYS_PARAM2 UNIQUE KEY (APP_ID, CAT_CD, PARAM_CD)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_bin
COMMENT = 'List of system parameters/properties.';

DROP TABLE IF EXISTS COM_REF_DATA_I18N;
DROP TABLE IF EXISTS COM_REF_DATA;
CREATE TABLE COM_REF_DATA ( 
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	UUID			VARCHAR(50) NOT NULL COMMENT 'Unique record identifier.',
	APP_ID			VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	CAT_CD			VARCHAR(100) NOT NULL COMMENT 'Category code.',
	REF_CD			VARCHAR(100) NOT NULL COMMENT 'Reference key.',
	REF_VALUE		VARCHAR(255) NOT NULL COMMENT 'Reference value, in English. The default value if value not defined for other locales.',	
	REF_DESC		VARCHAR(500) NOT NULL COMMENT 'Description of this reference data. Viewed by admin only.',
	
	SEQ_NO 			INTEGER NOT NULL DEFAULT 1 COMMENT 'Sequence number, for sorting items in a drop down list.',
	STATUS_CD		VARCHAR(3) NOT NULL DEFAULT 'A' COMMENT 'Status code to enable/disable records.',
	IS_DEFAULT		VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Flag to determine a record to be default in the drop down list.',
	IS_DISPLAY		VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Flag to display/hide record.',
	
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT PK_COM_REF_DATA PRIMARY KEY(ID),
	CONSTRAINT UK_COM_REF_DATA1 UNIQUE KEY (UUID),
	CONSTRAINT UK_COM_REF_DATA2 UNIQUE KEY (APP_ID, CAT_CD, REF_CD)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_bin
COMMENT = 'Reference data master table.';

CREATE TABLE COM_REF_DATA_I18N ( 
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	U_REF_DATA		VARCHAR(50) NOT NULL COMMENT 'Foreign key to ref_data table (master)',			
	LOCALE_CD		VARCHAR(25) NOT NULL COMMENT 'Locale code. (e.g. zh_MY = Chinese for MY, zh_HK_Trad = Traditional Chinese for HK)',
	REF_VALUE		VARCHAR(255) NOT NULL COMMENT 'Reference data value.',
	
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT PK_COM_REF_DATA_I18N PRIMARY KEY (ID),
	CONSTRAINT UK_COM_REF_DATA_I18N UNIQUE KEY (U_REF_DATA, LOCALE_CD),
	CONSTRAINT FK_COM_REF_DATA_I18N FOREIGN KEY (U_REF_DATA) REFERENCES COM_REF_DATA (UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_bin
COMMENT = 'Reference data child table for internationalisation.';

DROP TABLE IF EXISTS SEC_USER_ROLE;
DROP TABLE IF EXISTS SEC_USER;
CREATE TABLE SEC_USER ( 
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	UUID			VARCHAR(50) NOT NULL COMMENT 'Unique record identifier.',
	APP_ID			VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	
	STATUS_CD		VARCHAR(3) NOT NULL DEFAULT 'A' COMMENT 'Status of this user.',
	LOGIN_ID		VARCHAR(20) NOT NULL COMMENT 'Login ID',
	LOGIN_PSWD		VARCHAR(50) COMMENT 'User password for login.',
	USER_NAME		VARCHAR(50) NOT NULL COMMENT 'The user''s full name. To be used when updating CREATED_BY/UPD_BY columns.',
	NICKNAME		VARCHAR(50) COMMENT 'User''s preferred name to display on screen.',
	
	USER_ACCT_ID	VARCHAR(50) COMMENT 'User account ID (if require many user logins to single account relationship)',
	
	DT_FIRST_LOGIN			DATETIME COMMENT 'First login TIMESTAMP.',
	DT_LAST_LOGIN			DATETIME COMMENT 'Last login TIMESTAMP.',
	DT_LAST_PSWD_CHG		DATETIME COMMENT 'Last password change TIMESTAMP.',
	LOGIN_INVALID_COUNT		INTEGER NOT NULL DEFAULT 0 COMMENT 'Login invalid (due to wrong user/password) counter. Used to lock accounts when exceeded.',
	LOGIN_SUCCESS_COUNT		INTEGER NOT NULL DEFAULT 0 COMMENT 'Successful logins count.',
	
	EMAIL					VARCHAR(50) COMMENT 'The user''s email address.',
	MOBILE_NO				VARCHAR(15) COMMENT 'The user''s mobile number.',
	
	REMARKS			VARCHAR(100),
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_USER UNIQUE KEY (UUID),
	CONSTRAINT UK_SEC_USER_LOGIN UNIQUE KEY (APP_ID, LOGIN_ID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of users that can access this application.';

DROP TABLE IF EXISTS SEC_ROLE_FUNC_ACT;
DROP TABLE IF EXISTS SEC_ROLE_FUNC;
DROP TABLE IF EXISTS SEC_ROLE;
CREATE TABLE SEC_ROLE (
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	UUID			VARCHAR(50) NOT NULL COMMENT 'Unique record identifier.',
	APP_ID			VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	
	ROLE_CD			VARCHAR(50) NOT NULL COMMENT 'The role code.',
	ROLE_NAME		VARCHAR(250) NOT NULL COMMENT 'A short description of this role.',
	ORDER_SEQ_NO	INT(1) NOT NULL DEFAULT 1 COMMENT 'Role order sequence number. A user may have one or more roles, the default function (landing page) will be determined by the user role with the lowest sequence number.',
	STATUS_CD		VARCHAR(3) NOT NULL DEFAULT 'A',
	
	REMARKS			VARCHAR(250),
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_ROLE UNIQUE KEY (UUID),
	CONSTRAINT UK_SEC_ROLE_CD UNIQUE KEY (APP_ID, ROLE_CD)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of security roles in this application.';

DROP TABLE IF EXISTS SEC_FUNC_I18N;
DROP TABLE IF EXISTS SEC_FUNC;
CREATE TABLE SEC_FUNC (
	ID           		BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	UUID				VARCHAR(50) NOT NULL COMMENT 'Unique record identifier.',
	APP_ID				VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	
	FUNC_CD				VARCHAR(50) NOT NULL COMMENT 'The function code.',
	FUNC_NAME			VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'The function name to be displayed on screen, in DEFAULT language.',
	TYPE_CD				VARCHAR(10) NOT NULL DEFAULT 'L' COMMENT 'T = Title, L = Listing, H = Hidden. Value to be used in the template to generate the menu.',
	URI_ENTRY			VARCHAR(100) NOT NULL DEFAULT '#' COMMENT 'Entry URI for a function, to be used in the menu as a hyperlink.',
	URI_PROCESS			VARCHAR(250) COMMENT 'Regex for URIs to be mapped to this function, in addition to URI_ENTRY.',
	IS_SECURE			VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'If Y, then user must be authenticated to access this function. Set N for anonymous resources.',
	LEVEL_NO			INTEGER NOT NULL DEFAULT 1 COMMENT 'Used to determine the level of a function in the menu hierarchy. Top level = 1.',
	SEQ_NO				INTEGER NOT NULL DEFAULT 1 COMMENT 'Used for sorting the functions in the menu listing.',
	U_PARENT_FUNC		VARCHAR(50) COMMENT 'The parent records''s UUID value.',
	STATUS_CD			VARCHAR(3) NOT NULL DEFAULT 'A' COMMENT 'Status code of this function.',
	
	REMARKS			VARCHAR(250),
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_FUNC UNIQUE KEY (UUID),
	CONSTRAINT UK_SEC_FUNC_CD UNIQUE KEY (APP_ID, FUNC_CD)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of available functions in this application.';

CREATE TABLE SEC_FUNC_I18N (
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	U_FUNC			VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing sec_func.uuid',
	LOCALE_CD		VARCHAR(25) NOT NULL COMMENT 'Locale code. (e.g. zh_MY = Chinese for MY, zh_HK_Trad = Traditional Chinese for HK)',
	FUNC_NAME		VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
	
	REMARKS			VARCHAR(250),
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_FUNC_I18N_LOC UNIQUE KEY (U_FUNC, LOCALE_CD),
	CONSTRAINT FK_SEC_FUNC_I18N FOREIGN KEY(U_FUNC) REFERENCES SEC_FUNC(UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'Function names in other locales.';

CREATE TABLE SEC_USER_ROLE (
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	U_USER			VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing sec_user.uuid',
	U_ROLE			VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing sec_role.uuid',
	
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_USER_ROLE UNIQUE KEY (U_USER, U_ROLE),
	CONSTRAINT FK_SEC_UR_USER FOREIGN KEY(U_USER) REFERENCES SEC_USER(UUID),
	CONSTRAINT FK_SEC_UR_ROLE FOREIGN KEY(U_ROLE) REFERENCES SEC_ROLE(UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of user-role mappings.';

CREATE TABLE SEC_ROLE_FUNC (
	ID           	BIGINT(10) AUTO_INCREMENT NOT NULL COMMENT 'Auto incremental ID and PK for this table.',
	U_ROLE			VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing sec_role.uuid',
	U_FUNC			VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing sec_func.uuid',
	
	PRIMARY KEY(ID),
	CONSTRAINT UK_SEC_ROLE_FUNC UNIQUE KEY (U_ROLE, U_FUNC),
	CONSTRAINT FK_SEC_RF_ROLE FOREIGN KEY(U_ROLE) REFERENCES SEC_ROLE(UUID),
	CONSTRAINT FK_SEC_RF_FUNC FOREIGN KEY(U_FUNC) REFERENCES SEC_FUNC(UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of role-function mappings.';

DROP TABLE IF EXISTS SEC_LOGIN_SESSION;
CREATE TABLE SEC_LOGIN_SESSION (
	APP_ID			VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	LOGIN_ID		VARCHAR(50) NOT NULL COMMENT 'User login ID (SEC_USER.LOGIN_ID).',
	SESSION_ID		VARCHAR(50) NOT NULL COMMENT 'The HTTP session ID.',
	CHANNEL_CD		VARCHAR(20) NOT NULL DEFAULT 'WEB' COMMENT 'The channel code of this login session.',
	ENVIRONMENT		VARCHAR(50) NOT NULL DEFAULT 'localhost' COMMENT 'Server host name. Useful when application is deployed to a clustered environment.',
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DT_UPD     		DATETIME NOT NULL COMMENT 'Last activity timestamp. Default is turned off. Can be turned on for small/medium sized system.',
	CONSTRAINT UK_LOGIN_SESSION UNIQUE (APP_ID, LOGIN_ID, SESSION_ID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'List of currently logged in users.';

DROP VIEW IF EXISTS VW_SEC_ROLE_FUNC;
CREATE VIEW VW_SEC_ROLE_FUNC AS
SELECT RF.ID, R.APP_ID, R.ROLE_CD, R.ROLE_NAME, R.STATUS_CD AS ROLE_STATUS_CD, F.STATUS_CD AS FUNC_STATUS_CD, F.FUNC_CD, F.FUNC_NAME,
RF.U_FUNC, RF.U_ROLE
FROM SEC_ROLE R, SEC_ROLE_FUNC RF, SEC_FUNC F
WHERE R.UUID = RF.U_ROLE
AND F.UUID = RF.U_FUNC;

DROP VIEW IF EXISTS VW_SEC_USER_ROLE;
CREATE VIEW VW_SEC_USER_ROLE AS 
SELECT UR.ID, R.APP_ID, R.STATUS_CD AS ROLE_STATUS_CD, R.ORDER_SEQ_NO AS ROLE_ORDER_SEQ_NO, U.LOGIN_ID, R.ROLE_CD, R.ROLE_NAME, UR.U_USER, UR.U_ROLE
FROM SEC_USER U, SEC_ROLE R, SEC_USER_ROLE UR
WHERE U.UUID = UR.U_USER
AND R.UUID = UR.U_ROLE;

DROP VIEW IF EXISTS VW_SEC_FUNC;
CREATE VIEW VW_SEC_FUNC AS
SELECT PARENT.FUNC_CD AS PARENT_FUNC_CD, CHILD.*
FROM SEC_FUNC CHILD LEFT JOIN SEC_FUNC PARENT
ON CHILD.U_PARENT_FUNC = PARENT.UUID;

ALTER TABLE SEC_ROLE_FUNC ADD COLUMN IS_DEFAULT CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Is this default function for this role?';

DROP VIEW IF EXISTS VW_SEC_ROLE_FUNC;
CREATE VIEW VW_SEC_ROLE_FUNC AS
SELECT RF.ID, R.APP_ID, R.ROLE_CD, R.ROLE_NAME, R.STATUS_CD AS ROLE_STATUS_CD, R.ORDER_SEQ_NO AS ROLE_ORDER_SEQ_NO, 
F.STATUS_CD AS FUNC_STATUS_CD, F.FUNC_CD, F.FUNC_NAME, F.URI_ENTRY,
RF.U_FUNC, RF.U_ROLE, RF.IS_DEFAULT
FROM SEC_ROLE R, SEC_ROLE_FUNC RF, SEC_FUNC F
WHERE R.UUID = RF.U_ROLE
AND F.UUID = RF.U_FUNC;

DROP TABLE IF EXISTS AUDIT_DETAIL;
DROP TABLE IF EXISTS AUDIT_SUMMARY;
CREATE TABLE AUDIT_SUMMARY ( 
	ID           		BIGINT(10) AUTO_INCREMENT NOT NULL,
	UUID				VARCHAR(50) NOT NULL,
	APP_ID				VARCHAR(10) NOT NULL DEFAULT '*' COMMENT 'Application identifier.',
	
	REQUEST_ID			VARCHAR(50) NOT NULL COMMENT 'Request identifier. If one was not passed in, a UUID will be assigned by the server.',
	CHANNEL_CD			VARCHAR(20) NOT NULL DEFAULT 'WEB' COMMENT 'The channel code of this login session.',
	ENVIRONMENT			VARCHAR(50) NOT NULL DEFAULT 'localhost' COMMENT 'Server host name. Useful when application is deployed to a clustered environment.',
	SESSION_ID			VARCHAR(50) NOT NULL COMMENT 'The HTTP session ID.',
	SESSION_GROUP_ID	VARCHAR(50) NOT NULL COMMENT 'Value of shaHex(LOGIN_ID|SESSION_ID). To be used when querying list of audit logs for a particular user session (e.g. Logout Summary).',
	
	ERROR_CD          	VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Error code.',
	ERROR_DESC         	VARCHAR(250) COMMENT 'Error message.',
	TYPE_CD          	VARCHAR(20) NOT NULL DEFAULT 'INQ' COMMENT 'Refer to COM_REF_DATA.CAT_CD(AUDIT_TYPE_CD)',
    FUNC_CD          	VARCHAR(50) NOT NULL COMMENT 'Refer to SEC_FUNC(FUNC_CD)',
	EVENT_CD          	VARCHAR(20) NOT NULL DEFAULT 'INQ' COMMENT 'Refer to COM_REF_DATA.CAT_CD(AUDIT_EVENT_CD)',
	STATUS_CD			VARCHAR(3) NOT NULL DEFAULT 'H' COMMENT 'Refer to COM_REF_DATA.CAT_CD(AUDIT_STATUS_CD)',
	
	U_SEC_USER 			VARCHAR(50) NOT NULL,
	LOGIN_ID          	VARCHAR(50) NOT NULL,
	USER_NAME			VARCHAR(500) NOT NULL,
	
	CUSTOM_VAR_01		VARCHAR(250),
	CUSTOM_VAR_02		VARCHAR(250),
	CUSTOM_VAR_03		VARCHAR(250),
	CUSTOM_VAR_04		VARCHAR(250),
	CUSTOM_VAR_05		VARCHAR(250),
	CUSTOM_DEC_01		DECIMAL(25, 4),
	CUSTOM_DEC_02		DECIMAL(25, 4),
	CUSTOM_DEC_03		DECIMAL(25, 4),
	CUSTOM_DEC_04		DECIMAL(16,6),
	CUSTOM_DEC_05		DECIMAL(16,6),
	CUSTOM_DT_01		DATETIME,
	CUSTOM_DT_02		DATETIME,
	
	REMARKS			VARCHAR(250),
	DT_CREATED     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY      VARCHAR(50) NOT NULL,
	DT_UPD       	DATETIME NOT NULL,
	UPD_BY       	VARCHAR(50) NOT NULL,
	VERSION			INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(ID),
	CONSTRAINT UK_AUD_SUMMARY UNIQUE KEY (UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'Audit log summary';

CREATE TABLE AUDIT_DETAIL (
    ID  				BIGINT(10) AUTO_INCREMENT NOT NULL,
	U_AUDIT_SUMMARY		VARCHAR(50) NOT NULL COMMENT 'Foreign key referencing AUDIT_SUMMARY.UUID',
	CONTENT				TEXT NOT NULL COMMENT 'Audit details, in XML.',
    CONSTRAINT PK_AUD_DETAIL PRIMARY KEY(ID),
	CONSTRAINT UK_AUD_DETAIL UNIQUE (U_AUDIT_SUMMARY),
	CONSTRAINT FK_AUD_DETAIL FOREIGN KEY(U_AUDIT_SUMMARY) REFERENCES AUDIT_SUMMARY(UUID)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'Audit log details (in XML)';

-- security roles
INSERT INTO sec_role(UUID, ROLE_CD, ROLE_NAME, REMARKS, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('ROLE_ADMIN', 'ADMIN', 'Administrator', 'System administrator', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_role(UUID, ROLE_CD, ROLE_NAME, ORDER_SEQ_NO, REMARKS, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('ROLE_USER', 'USER', 'User', 99, 'The default role for all registered users in the system', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_role(UUID, ROLE_CD, ROLE_NAME, REMARKS, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('ROLE_SUPER_USER', 'SUPER_USER', 'Super User', 'Has access to all areas of the system', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
	

-- default super user
INSERT INTO sec_user(UUID, LOGIN_ID, LOGIN_PSWD, USER_NAME, EMAIL, MOBILE_NO, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('superman', 'superman', 'ab6dca30127a382eb33930fc7f7339c0dc2d56c9', 'Super User', 'dev@bcs.com', '+60', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_user(UUID, LOGIN_ID, LOGIN_PSWD, USER_NAME, EMAIL, MOBILE_NO, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('klhai', 'klhai', '7e23c6338b8e8d1ad74d13e46ed6e5fb720d1636', 'Super User', 'klhai@bcs.com', '+60', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_user(UUID, LOGIN_ID, LOGIN_PSWD, USER_NAME, EMAIL, MOBILE_NO, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('pghai', 'pghai', '69b218d015fec035d6d4496ff31b9023dcf4b409', 'Super User', 'pghai@bcs.com', '+60', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- user-role mapping for super user
INSERT INTO sec_user_role (U_USER, U_ROLE) VALUES ('superman', 'ROLE_SUPER_USER');
INSERT INTO sec_user_role (U_USER, U_ROLE) VALUES ('klhai', 'ROLE_SUPER_USER');
INSERT INTO sec_user_role (U_USER, U_ROLE) VALUES ('pghai', 'ROLE_SUPER_USER');

-- default functions
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
  VALUES('U_USER_ACCT', 'USER_ACCT', 'My Account', '', '#', '', '1', 1, 98, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
  VALUES('U_CHANGE_PSWD', 'CHANGE_PSWD', 'Change Password', 'L', '/app/user/pswd', '', '1', 2, 1, 'U_USER_ACCT', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
  VALUES('U_LOGOUT', 'LOGOUT', 'Logout', '', '/app/doLogout', '', '1', 1, 99, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

  
-- default role-function mappings
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_USER_ACCT', 'ROLE_USER');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_CHANGE_PSWD', 'ROLE_USER');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_LOGOUT', 'ROLE_USER');

-- create table sec_role_func_act
CREATE TABLE `SEC_ROLE_FUNC_ACT` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'Auto incremental ID and PK for this table.',
  `U_ROLE` varchar(50) NOT NULL COMMENT 'Foreign key referencing sec_role.uuid',
  `U_FUNC` varchar(50) NOT NULL COMMENT 'Foreign key referencing sec_func.uuid',
  `ACTION_CD` varchar(50) NOT NULL COMMENT 'Foreign key referencing sec_act.uuid',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_SEC_ROLE_FUNC` (`U_ROLE`,`U_FUNC`,`ACTION_CD`),
  KEY `FK_SEC_RF_FUNC` (`U_FUNC`),
  CONSTRAINT `FK_SEC_RFA_ROLE` FOREIGN KEY (`U_ROLE`) REFERENCES `SEC_ROLE` (`UUID`),
  CONSTRAINT `FK_SEC_RFA_FUNC` FOREIGN KEY (`U_FUNC`) REFERENCES `SEC_FUNC` (`UUID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 COMMENT='List of role-function-action mappings.';

-- default ref data
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_STATUS_ACTIVE', 'STATUS', 'A', 'Active', 'Active status', 1, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_STATUS_TERMINATED', 'STATUS', 'T', 'Terminated', 'Terminated status', 2, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_STATUS_SUSPENDED', 'STATUS', 'S', 'Suspended', 'Suspended status', 3, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_FUNC_TYPE_CD_TITLE', 'FUNC_TYPE_CD', 'T', 'Title', 'First level menu title', 1, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_FUNC_TYPE_CD_LIST', 'FUNC_TYPE_CD', 'L', 'List', 'Menu items', 2, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_FUNC_TYPE_CD_HIDDEN', 'FUNC_TYPE_CD', 'H', 'Hidden', 'Functions not listed in the menu', 3, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_ACT_TYPE_CD_ADD', 'ACT_TYPE_CD', 'ADD', 'Add', 'Action for add new record', 1, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_ACT_TYPE_CD_DEL', 'ACT_TYPE_CD', 'DEL', 'Delete', 'Action for delete existing record', 2, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_ACT_TYPE_CD_UPD', 'ACT_TYPE_CD', 'UPD', 'Update', 'Action for update existing record', 3, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO COM_REF_DATA (UUID, CAT_CD, REF_CD, REF_VALUE, REF_DESC, SEQ_NO, CREATED_BY, UPD_BY, DT_UPD)
    VALUES ('U_ACT_TYPE_CD_PRINT', 'ACT_TYPE_CD', 'PRINT', 'Print', 'Action for print records', 4, 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- default admin user
INSERT INTO sec_user(UUID, LOGIN_ID, LOGIN_PSWD, USER_NAME, EMAIL, MOBILE_NO, CREATED_BY, UPD_BY, DT_UPD) 
    VALUES('U_ADMIN', 'admin', '102382b79c4eeb26efb917fd38e4ddac72e9b2a8', 'Admin', 'dev@bcs.com', '+60', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- default admin function
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ADMIN', 'ADMIN', 'Administration', 'T', '#', '', '1', 1, 97, NULL, 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_ADMIN_SECURITY', 'ADMIN_SECURITY', 'Security', '', '#', '', '1', 2, 1, 'U_ADMIN', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SEC_USER', 'SEC_USER', 'Users', '', '/app/cfg/sec/user', '', '1', 3, 1, 'U_ADMIN_SECURITY', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SEC_ROLE', 'SEC_ROLE', 'Roles', '', '/app/cfg/sec/role', '', '1', 3, 2, 'U_ADMIN_SECURITY', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SEC_FUNC', 'SEC_FUNC', 'Functions', '', '/app/cfg/sec/func', '', '1', 3, 3, 'U_ADMIN_SECURITY', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SEC_ROLE_FUNC', 'SEC_ROLE_FUNC', 'Role-Function Mapping', '', '/app/cfg/sec/role/func', '', '1', 3, 4, 'U_ADMIN_SECURITY', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO sec_func(UUID, FUNC_CD, FUNC_NAME, TYPE_CD, URI_ENTRY, URI_PROCESS, IS_SECURE, LEVEL_NO, SEQ_NO, U_PARENT_FUNC, STATUS_CD, REMARKS, CREATED_BY, UPD_BY, DT_UPD)
	VALUES('U_SEC_ROLE_FUNC_ACT', 'SEC_ROLE_FUNC_ACT', 'Role-Function-Action Mapping', '', '/app/cfg/sec/role/func/act', '', '1', 3, 5, 'U_ADMIN_SECURITY', 'A', '', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP);

-- default admin user-role mapping
INSERT INTO sec_user_role (U_USER, U_ROLE) VALUES ('U_ADMIN', 'ROLE_ADMIN');
INSERT INTO sec_user_role (U_USER, U_ROLE) VALUES ('U_ADMIN', 'ROLE_USER');

-- default admin role-function mapping
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_ADMIN', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_ADMIN_SECURITY', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_SEC_USER', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_SEC_ROLE', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_SEC_FUNC', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_SEC_ROLE_FUNC', 'ROLE_ADMIN');
INSERT INTO sec_role_func (U_FUNC, U_ROLE) VALUES ('U_SEC_ROLE_FUNC_ACT', 'ROLE_ADMIN');

COMMIT;