################
#	   E-INVOICE    #	
################

envbaseurl.sandbox=https://preprod.myinvois.hasil.gov.my/
envbaseurl.actual=https://myinvois.hasil.gov.my/

system.api.sandbox=https://preprod-api.myinvois.hasil.gov.my/
system.api.actual=https://api.myinvois.hasil.gov.my/

api.login=/connect/token
api.validate=/api/v1.0/taxpayer/validate
api.submit=/api/v1.0/documentsubmissions

# api url controller
# true = testing mode, use sandbox
# false = production mode, use actual url
testing=true

# if false, scheduler won't run at app startup
scheduler=false